# Generated by Django 6.0.6 on 2026-06-07 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(choices=[('A1', 'Beginner A1'), ('A2', 'Elementary A2'), ('B1', 'Pre-Intermediate B1'), ('B2', 'Intermediate B2'), ('C1', 'Upper-Intermediate C1'), ('C2', 'Advanced C2')], max_length=2)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('icon', models.CharField(default='📚', max_length=50)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('grammar_explanation', models.TextField(blank=True)),
                ('examples', models.TextField(blank=True)),
                ('youtube_url', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.level')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
